batch_size: 32
ckpt_mode: max
confidence_th: 0.499999
dataset_stats: imagenet
exp_name: SLL-pretrained-resnet-layer34fc-conf0499999
freeze_layers: true
k_ckpts: 1
lr: 1e-4
metric_names:
- avg_CE
- avg_Acc
- tp
- fp
- fn
- precision
- recall
- f1_score
model_name: PretrainedResNet
momentum: null
monitor_metric: val/avg_Acc
nbr_classes: 1
nbr_warmup_batches: 35
num_epochs: 10
num_ssl_iters: 5
optimizer_name: Adam
p_hor_flip: 0.5
p_ver_flip: 0.5
path2ckpt: checkpoints/Pretrained_resnet18_unfr_layer3_layer4_fc_lr0.0001_medium_augs_rot15_nojitter_imagenet_norms_warmup45_scheduler_epochs20/checkpoint_epoch_16.pth
positive_cls_thr: 0.5
pretrained_resnet: resnet18
rand_rot_degree: 15
saving_path: checkpoints/
sch_gamma: 0.5
sch_step: 30
seed: 42
test_data_path: ./data/test/
train_data_path: ./data/train/
unfreeze_layers_list:
- layer3
- layer4
- fc
unlabelled_data_path: ./data/unlabelled/
val_data_path: ./data/val/
weight_decay: 1e-4
