exp_name: '${model_name}_medium_augs_rot${rand_rot_degree}_wjitter_${dataset_stats}_norms_warmup${nbr_warmup_batches}_scheduler_epochs${sch_step}'
seed: 42

# Model
model_name: 'CustomResNet'
architecture_list: 
  # - [conv, 3, 32]
  - [conv, 3, 64]
  # MaxPool
  # - [conv, 32, 64]
  - [conv, 64, 64]
  - [conv, 64, 64]
  - [pool, 64, 128]
  - [conv, 128, 128]
  - [pool, 128, 256]
  - [conv, 256, 256]
nbr_classes: 1
pretrained_checkpoint: 
load_optimizer:
positive_cls_thr: 0.5

# Data
dataset_stats: 'unlabelled'
train_data_path: './data/train/'
val_data_path: './data/val/'
test_data_path: './data/test/'

p_hor_flip: 0.5
p_ver_flip: 0.5
rand_rot_degree: 15

# Training 
batch_size: 32
optimizer_name: 'Adam'
lr: 1e-3
weight_decay: 1e-4
momentum:
sch_step: 30
sch_gamma: 0.5
nbr_warmup_batches: 15
num_epochs: 100

saving_path: 'checkpoints/'
monitor_metric: 'val/avg_Acc'
k_ckpts: 3
ckpt_mode: 'max'

metric_names: ['avg_CE', 'avg_Acc', 'tp', 'fp', 'fn', 'precision' , 'recall', 'f1_score']



